### ISSUE TITLE
InjectionManager doesn't activate ProjectContext in a build

### ISSUE THREAD

**Issue by vvrvvd** [BroWar-Collective/Unity-Injection#6]
#if UNITY_EDITOR
            if (prefabWasActive)
            {
                //NOTE: this ensures the prefab's Awake() methods don't fire (and, if in the Editor, that the prefab file doesn't get modified)
                instance = Instantiate(projectContextPrefab, ZenUtilInternal.GetOrCreateInactivePrefabParent());
                instance.gameObject.SetActive(false);
                instance.transform.SetParent(null, false);
                instance.gameObject.SetActive(true);
            }
            else
            {
                instance = Instantiate(projectContextPrefab);
            }
#else
            if (prefabWasActive)
            {
                **projectContextPrefab.gameObject.SetActive(false);
                instance = Instantiate(projectContextPrefab);
                projectContextPrefab.gameObject.SetActive(true);**
            }
            else
            {
                instance = Instantiate(projectContextPrefab);
            }
#endif

instance never get activated.

**Comment by arimger** [comment]
Fixed in https://github.com/BroWar-Collective/Unity-Injection/pull/7.
